@SharePoint.Api_HostAddress = http://localhost:5247
@AccessToken = REPLACE_WITH_BEARER_TOKEN

### Create folder
POST {{SharePoint.Api_HostAddress}}/api/folders
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
	"name": "Projects",
	"parentId": null
}

### List documents in a folder (or root when null)
GET {{SharePoint.Api_HostAddress}}/api/documents?parentId=
Accept: application/json
Authorization: Bearer {{AccessToken}}

### Upload file to root
POST {{SharePoint.Api_HostAddress}}/api/files/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{AccessToken}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="sample.txt"
Content-Type: text/plain

hello sharepoint
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
